management:
  info:
    java:
      enabled: true
    git:
      mode: "full"
    os:
      enabled: true
    env:
      enabled: true
    server:
      port: 9292
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
#      show-details: always
      show-components: always

info:
  app:
    name: hello-actuator
    company: cw

logging:
  level:
    hello.controller: debug

server:
  tomcat:
    mbeanregistry:
      enabled: true